-- MySQL Script generated by MySQL Workbench
-- Sun Nov 30 21:22:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema travel_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `travel_db` ;

-- -----------------------------------------------------
-- Table `travel_db`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`board` (
  `board_id` INT NOT NULL AUTO_INCREMENT,
  `board_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`board_id`),
  UNIQUE INDEX `board_name` (`board_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`chatroom` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(255) NOT NULL,
  `creator_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  `status` ENUM('ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`chatroommember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`chatroommember` (
  `room_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`room_id`, `user_id`),
  UNIQUE INDEX `chatroommember_user_id_room_id_unique` (`room_id` ASC, `user_id` ASC) VISIBLE,
  UNIQUE INDEX `chatroommember_room_id_user_id` (`room_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `chatroommember_ibfk_1`
    FOREIGN KEY (`room_id`)
    REFERENCES `travel_db`.`chatroom` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chatroommember_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `travel_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `view_count` INT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `board_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `board_id` (`board_id` ASC) VISIBLE,
  CONSTRAINT `post_ibfk_45`
    FOREIGN KEY (`user_id`)
    REFERENCES `travel_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_ibfk_46`
    FOREIGN KEY (`board_id`)
    REFERENCES `travel_db`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  CONSTRAINT `comment_ibfk_45`
    FOREIGN KEY (`user_id`)
    REFERENCES `travel_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comment_ibfk_46`
    FOREIGN KEY (`post_id`)
    REFERENCES `travel_db`.`post` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`trips` (
  `trip_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `view_count` INT NULL DEFAULT '0',
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`trip_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `trips_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `travel_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`trip_days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`trip_days` (
  `day_id` INT NOT NULL AUTO_INCREMENT,
  `day_index` INT NOT NULL COMMENT 'N일차 (1, 2, 3...)',
  `trip_date` DATE NULL DEFAULT NULL,
  `trip_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`day_id`),
  UNIQUE INDEX `trip_days_trip_id_day_index` (`trip_id` ASC, `day_index` ASC) VISIBLE,
  CONSTRAINT `trip_days_ibfk_1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `travel_db`.`trips` (`trip_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`day_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`day_stops` (
  `stop_id` INT NOT NULL AUTO_INCREMENT,
  `stop_order` INT NOT NULL COMMENT '방문 순서',
  `location_name` VARCHAR(255) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `memo` TEXT NULL DEFAULT NULL,
  `day_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`stop_id`),
  INDEX `day_id` (`day_id` ASC) VISIBLE,
  CONSTRAINT `day_stops_ibfk_1`
    FOREIGN KEY (`day_id`)
    REFERENCES `travel_db`.`trip_days` (`day_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travel_db`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_db`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `room_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `message_ibfk_45`
    FOREIGN KEY (`room_id`)
    REFERENCES `travel_db`.`chatroom` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `message_ibfk_46`
    FOREIGN KEY (`user_id`)
    REFERENCES `travel_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
